apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: ot-knowledge-mcp-secrets
spec:
  hostAPI: https://infisical.6cclab.dev/api
  syncConfig:
    resyncInterval: 60s
  authentication:
    kubernetesAuth:
      identityId: ccebb465-42d4-4b19-9dac-9eec7a9e5613
      serviceAccountRef:
        name: default
        namespace: ot-mcp-dev
  managedKubeSecretReferences:
    - secretName: ot-knowledge-mcp-secrets
      secretNamespace: ot-mcp-dev
      creationPolicy: Owner
      template:
        includeAllSecrets: true
        secretType: Opaque
  authentication:
    kubernetesAuth:
      identityId: ccebb465-42d4-4b19-9dac-9eec7a9e5613
      serviceAccountRef:
        name: default
        namespace: ot-mcp-dev
      secretsScope:
        projectSlug: ""
        envSlug: dev
        secretsPath: /
        recursive: true
