apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: ot-knowledge-mcp-secrets
spec:
  hostAPI: https://infisical.6cclab.dev/api
  resyncInterval: 60
  authentication:
    kubernetesAuth:
      identityId: ccebb465-42d4-4b19-9dac-9eec7a9e5613
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: default
        namespace: ot-mcp-dev
      secretsScope:
        projectId: 0cb2582c-ba4d-4d26-8c7f-518f07cb387f
        envSlug: dev
        secretsPath: /
        recursive: true
  managedKubeSecretReferences:
    - secretName: ot-knowledge-mcp-secrets
      secretNamespace: ot-mcp-dev
      creationPolicy: Owner
      secretType: Opaque
      template:
        includeAllSecrets: true
