apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/anpato/ot-knowledge-mcp
  newName: ghcr.io/anpato/ot-knowledge-mcp
  newTag: 92a73e491d03adc083e28ee0f7e7ae037dea7363

patches:
- path: ./deployment.yaml

resources:
- ../../base
- ingress.yaml
