apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/anpato/ot-knowledge-mcp
  newName: ghcr.io/anpato/ot-knowledge-mcp
  newTag: c80dfd9fafb75135eeb8b906a14a6164b5a03643

patches:
- path: ./deployment.yaml

resources:
- ../../base
- ingress.yaml
