apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: ghcr.io/anpato/ot-knowledge-mcp
    newName: ghcr.io/anpato/ot-knowledge-mcp
    newTag: 12005bee19492411c589c5c486ff7409d6e85d64

patches:
  - path: ./deployment.yaml
  - path: ./config.yaml
resources:
  - ../../base
  - ingress.yaml
