kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: ot-knowledge-mcp-hpa
  labels:
    app: ot-knowledge-mcp
spec:
  scaleTargetRef:
    kind: Deployment
    name: ot-knowledge-mcp
    apiVersion: apps/v1
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 100
          periodSeconds: 45
      selectPolicy: Max
